
name: Main 
on:
  
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        default: master
      deploy_message:
        description: Deploy Description
jobs:
  test:
    runs-on: ubuntu-latest
    

    steps:
      - uses: 280780363/sqlserver-action@v1.0
        with:
          accept eula: Y #Required, ACCEPT_EULA confirms your acceptance of the End-User Licensing Agreement.
          sa password: SqlSever123123 # Optional, default value is SqlSever123123.
      - name: Run sqlclient
        run: sqlcmd -S ${{secrets.SERVER}} -U ${{secrets.USERNAME}} -P ${{secrets.PASSWORD}} -i /${GITHUB_WORKSPACE}/sql/*.sql
        #run: sqlcmd -S localhost -U sa -P dbatools.I0 -i /${GITHUB_WORKSPACE}/sql/test.sql
        # run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "SELECT @@version;"
